/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aippt: typeof import('./src/components/aippt/index.vue')['default']
    BatchUsers: typeof import('./src/components/extend/BatchUsers.vue')['default']
    ForgotPassword: typeof import('./src/components/login/forgot-password.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    Myaccount: typeof import('./src/components/myaccount/index.vue')['default']
    Orgs: typeof import('./src/components/manage/Orgs.vue')['default']
    OrgsBtn: typeof import('./src/components/extend/OrgsBtn.vue')['default']
    Roles: typeof import('./src/components/manage/Roles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionOrgs: typeof import('./src/components/extend/SelectionOrgs.vue')['default']
    SelectionOrgsBtn: typeof import('./src/components/extend/SelectionOrgsBtn.vue')['default']
    SelectionUsers: typeof import('./src/components/extend/SelectionUsers.vue')['default']
    SignUp: typeof import('./src/components/login/sign-up.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    Users: typeof import('./src/components/manage/Users.vue')['default']
  }
}
