/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aippt: typeof import('./src/components/aippt/index.vue')['default']
    BatchUsers: typeof import('./src/components/extend/BatchUsers.vue')['default']
    DeleteConfirmationDialog: typeof import('./src/components/extend/DeleteConfirmationDialog.vue')['default']
    DeleteConfirmationDialogBtn: typeof import('./src/components/extend/DeleteConfirmationDialogBtn.vue')['default']
    ExportOrgs: typeof import('./src/components/extend/ExportOrgs.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    ForgotPasswordPanel: typeof import('./src/components/login/forgot-password-panel.vue')['default']
    ImportOrgs: typeof import('./src/components/extend/ImportOrgs.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    LoginPanel: typeof import('./src/components/login/login-panel.vue')['default']
    Myaccount: typeof import('./src/components/myaccount/index.vue')['default']
    Orgs: typeof import('./src/components/manage/Orgs.vue')['default']
    OrgsDetails: typeof import('./src/components/manage/OrgsDetails.vue')['default']
    ReviewOrgsBtn: typeof import('./src/components/extend/ReviewOrgsBtn.vue')['default']
    Roles: typeof import('./src/components/manage/Roles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionOrgs: typeof import('./src/components/extend/SelectionOrgs.vue')['default']
    SelectionOrgsBtn: typeof import('./src/components/extend/SelectionOrgsBtn.vue')['default']
    SelectionUsers: typeof import('./src/components/extend/SelectionUsers.vue')['default']
    SelectionUsersBtn: typeof import('./src/components/extend/SelectionUsersBtn.vue')['default']
    SignUpPanel: typeof import('./src/components/login/sign-up-panel.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    SSO: typeof import('./src/components/SSO.vue')['default']
    Users: typeof import('./src/components/manage/Users.vue')['default']
    VDateTimeInput: typeof import('./src/components/VDateTimeInput.vue')['default']
  }
}
